#{% raw %}
- hosts: all
  vars:
    db_url: postgresql://django:django@localhost:5432/django
    home: /vagrant
    db_user: '{{ db_url | urlsplit("username") }}'
    db_name: '{{ db_url | urlsplit("path") | replace("/", "", 1) }}'
    db_pass: '{{ db_url | urlsplit("password") }}'
  gather_facts: no
  pre_tasks:  # for ansible
    - raw: sudo apt-get install -y python-simplejson

  tasks:
    - lineinfile: path=.bashrc line='cd {{ home }}'

    - lineinfile: path=.bashrc line='. ./venv/bin/activate'

    - copy: src=../.env.example dest={{ home }}/.env force=no

    - file: path={{ home }}/.git/hooks state=directory

    - copy: src=../config/pre-commit dest={{ home }}/.git/hooks mode='a+x'

    - apt: pkg={{ item }}
      with_items: '{{ lookup("file", "../ci/apt-requirements.txt").splitlines() }}'
      become: true
      become_method: sudo

    - apt: name={{ item }}
      with_items: [
        postgresql,
        python-psycopg2,
        python3.6-venv,
        python3-pip,
      ]
      become: true
      become_true: sudo

    - pip:
        requirements: '{{ home }}/ci/py-requirements.txt'
        virtualenv: '{{ home }}/venv'
        virtualenv_command: /usr/bin/python3.6 -m venv

    - postgresql_user:
        name: '{{ db_user }}'
        password: '{{ db_pass }}'
        role_attr_flags: SUPERUSER
      become: true
      become_user: postgres
      become_method: sudo

    - postgresql_db:
        name: '{{ db_name }}'
        owner: '{{ db_user }}'
        encoding: UTF-8
      become: true
      become_user: postgres
      become_method: sudo

    - django_manage:
      args:
        command: migrate
        app_path: '{{ home }}'
        virtualenv: '{{ home }}/venv'
#{% endraw %}
