version: '2'
services:
  {{ cookiecutter.repo_name }}:
    build: .

  {{ cookiecutter.repo_name }}_nginx:
    image: nginx
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - './configs/nginx.conf:/etc/nginx/nginx.conf:ro'
    volumes_from:
      - '{{ cookiecutter.repo_name }}'
