- name: setup dev environment
  hosts: localhost
  connection: local
  vars:
    venv: ./venv

  tasks:
    - name: create .env file
      copy: src=./.env.example dest=./.env

    - name: Create dir for pre-commit hook
      file: path=./.git/hooks state=directory

    - name: create pre commit hook
      copy: src=./config/pre-commit dest=./.git/hooks mode='a+x'

    - pip:
      args:
        chdir: .
        requirements: ./ci/py-requirements.txt
        virtualenv: '{{ "{{ venv }}" }}'
        virtualenv_command: /usr/bin/python3.6 -m venv

    - django_manage:
      args:
        command: migrate
        app_path: .
        virtualenv: '{{ "{{ venv }}" }}'
